youtube:
  UCCCPCZNChQdGa9EkATeye4g: # France24
    89756262492803072: "@everyone ! **France24** vient juste de poster une vidéo !\n{{ video_link }}"

twitch:
  stream.online:
    86831929: # Maniarr_
      89756262492803072: "Le live vient de se lancer, Alors dépêche toi !\nhttps://twitch.tv/{{ broadcaster_login }}"
  stream.offline:
    86831929: # Maniarr_
      89756262492803072: "{{ broadcaster_name }} vient de terminer son live"
